### ISSUE TITLE
Bioc2023 plan

### ISSUE THREAD

**Issue by mikelove** [tidyomics/tidyomicsWorkshopBioc2023#1]
New thread for Bioc2023 plan

**Comment by mikelove** [comment]
@stemangiola I've added in some very hacky and ugly code, I will be working on this to make it safer and tidier, and coming up with a plausible biological case for working with plyranges and tidySCE

But it's building right now and trimmed down in terms of dependencies. It could use some trimming in terms of vignette content I think as we would run way over 45 minutes if you look at it.

**Comment by stemangiola** [comment]
thanks! sure i will have a think to what i can trim. after you add your case study we can have a better idra. i could trim part 3. we could have a short meeting to discuss these things.

**Comment by mikelove** [comment]
I know it's already weekend in Melbourne so feel free to ignore this until next week

remind me, how can I get access to rowData in tidySCE?

https://github.com/tidybiology/tidyomicsWorkshopBioc2023/blob/devel/vignettes/tidyomicsWorkshopBioc2023.Rmd#L445

**Comment by stemangiola** [comment]
Either

`sce |> rowData()`

`1sce |> pivot_transcript()`

at some point should become `pivot_feature()`

**Comment by mikelove** [comment]
Ok I got something working, i cut out part 3 for now, we can add it back if needed.

right now is still hacky but I’m gonna move the code toward: define categories of transcripts by their distance to PBMC ATAC peaks (close, medium, far, etc) and then plot pseudobulk counts per transcript category. I end up showing nesting and how to combine genomic and SCE. 

Still a few cludgey places but I’ll work on it this weekend.
